//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pssc.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PsscEntities : DbContext
    {
        public PsscEntities()
            : base("name=PsscEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DormList> DormList { get; set; }
        public virtual DbSet<LoginT> LoginT { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<StudentGrades> StudentGrades { get; set; }
    }
}
